name: CI

on:
  push:
    branches: master
  pull_request:
    types:
      - assigned
      - labeled
      - opened
      - edited
      - reopened
      - synchronize
jobs:
  build-macos:
    name: Build
    runs-on: macos-latest
    steps:
      - name: Checkout tap
        uses: actions/checkout@v2
      - name: Update Homebrew
        run: |
          rm -rf $(brew --repo homebrew/cask)
          rm -rf $(brew --repo homebrew/cask-versions)
          rm -rf $(brew --cellar)/*
          sudo rm -rf /usr/local/include/* /usr/local/lib/*
          brew update-reset
          brew cleanup
      - name: Set up tap
        run: |
          REPO=$(brew --repo ${{github.repository}})
          mkdir -p "$REPO"
          rm -rf "$REPO"
          ln -s $GITHUB_WORKSPACE "$REPO"
      - name: Run brew test-bot --only-setup
        run: brew test-bot --only-setup --tap=${{github.repository}} -v 
      - name: Run brew test-bot --only-formulae
        run: |
          mkdir ~/bottles
          cd ~/bottles
          brew test-bot --only-formulae --tap=${{github.repository}} -v
      - name: Output brew test-bot --only-formulae failures
        if: always()
        run: |
            cat ~/bottles/steps_output.txt
            rm ~/bottles/steps_output.txt
